site_name: Wall Clock In Machine
site_description: A physical desk button for automatic time tracking. No more curl commands!
site_author: Wall Clock In Machine Project
site_url: https://lanterno.github.io/office-wall-clock/

repo_name: lanterno/office-wall-clock
repo_url: https://github.com/lanterno/office-wall-clock
edit_uri: edit/main/docs-site/

# Use content from docs-site/ and output the built site into docs/ for GitHub Pages
docs_dir: docs-site
site_dir: docs

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Roboto
    code: Roboto Mono
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  
  icon:
    repo: fontawesome/brands/github
    logo: material/clock-fast

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lanterno/office-wall-clock
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lanterno
  
  version:
    provider: mike
    default: latest

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quick Start: getting-started/quick-start.md
    - Project Timeline: getting-started/timeline.md

  - Hardware:
    - Overview: hardware/overview.md
    - Specifications: hardware/specifications.md
    - Bill of Materials: hardware/bill-of-materials.md
    - Enclosure Design: hardware/enclosure-design.md
    - Wiring Diagram: hardware/wiring.md

  - Firmware:
    - Overview: firmware/overview.md
    - Architecture: firmware/architecture.md
    - Installation: firmware/installation.md
    - Configuration: firmware/configuration.md
    - API Integration: firmware/api-integration.md

  - Assembly:
    - Preparation: assembly/preparation.md
    - Component Testing: assembly/testing.md
    - Breadboard Prototype: assembly/breadboard.md
    - Soldering: assembly/soldering.md
    - Enclosure Assembly: assembly/enclosure.md
    - Final Testing: assembly/final-testing.md

  - Usage:
    - Daily Operation: usage/daily-operation.md
    - LED Indicators: usage/led-indicators.md
    - Battery Management: usage/battery.md
    - Maintenance: usage/maintenance.md

  - Deployment:
    - Quick Start: deployment/quick-start.md

copyright: Copyright &copy; 2025 Wall Clock In Machine Project
